### ISSUE TITLE
BoxConstraints error 

### ISSUE THREAD

**Issue by Ajit121** [LiewJunTung/pin_code_text_field#10]
I'm getting this issue in pin_code_text_field: ^1.3.2

The following assertion was thrown during performLayout():
I/flutter ( 4573): BoxConstraints has a negative minimum height.
I/flutter ( 4573): These invalid constraints were provided to RenderCustomPaint's layout() function by the following
I/flutter ( 4573): function, which probably computed the invalid constraints in question:
I/flutter ( 4573):   _RenderDecoration.performLayout (package:flutter/src/material/input_decorator.dart:1081:17)
I/flutter ( 4573): The offending constraints were:
I/flutter ( 4573):   BoxConstraints(w=0.1, h=-19.0; NOT NORMALIZED)

**Comment by LiewJunTung** [comment]
Thanks for the report. It seems was an update to the TextField's InputDecorator It is addressed in version `1.3.3`

**Comment by yudaprama** [comment]
@LiewJunTung I'm still getting this error with `1.3.5` with flutter channel `beta`

This is the code:
```
PinCodeTextField(
			      autofocus: true,
			      highlight: true,
			      pinBoxDecoration: ProvidedPinBoxDecoration.underlinedPinBoxDecoration,
			      pinTextStyle: TextStyle(
							fontWeight: FontWeight.bold,
							color: Colors.orange,
							fontSize: 20,
			      ),
			      defaultBorderColor: CupertinoColors.inactiveGray,
			      hasTextBorderColor: Colors.green,
			      highlightColor: Colors.orange,
			      maxLength: 6,
			      pinTextAnimatedSwitcherTransition: ProvidedPinBoxTextAnimation.scalingTransition,
			      pinBoxWidth: fieldWidth,
			      onDone: (code) async {

			      },
		      )
```

Here complete exception:
```
I/flutter ( 8356): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 8356): The following assertion was thrown during performLayout():
I/flutter ( 8356): BoxConstraints has a negative minimum height.
I/flutter ( 8356): These invalid constraints were provided to RenderCustomPaint's layout() function by the following
I/flutter ( 8356): function, which probably computed the invalid constraints in question:
I/flutter ( 8356):   _RenderDecoration.performLayout (package:flutter/src/material/input_decorator.dart:1080:17)
I/flutter ( 8356): The offending constraints were:
I/flutter ( 8356):   BoxConstraints(w=0.1, h=-19.0; NOT NORMALIZED)
I/flutter ( 8356):
I/flutter ( 8356): When the exception was thrown, this was the stack:
I/flutter ( 8356): #0      BoxConstraints.debugAssertIsValid.<anonymous closure>.throwError (package:flutter/src/rendering/box.dart:504:9)
I/flutter ( 8356): #1      BoxConstraints.debugAssertIsValid.<anonymous closure> (package:flutter/src/rendering/box.dart:534:19)
I/flutter ( 8356): #2      BoxConstraints.debugAssertIsValid (package:flutter/src/rendering/box.dart:551:6)
I/flutter ( 8356): #3      RenderObject.layout (package:flutter/src/rendering/object.dart:1559:24)
I/flutter ( 8356): #4      _RenderDecoration.performLayout (package:flutter/src/material/input_decorator.dart:1080:17)
I/flutter ( 8356): #5      RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 8356): #6      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8356): #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 8356): #8      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8356): #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 8356): #10     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8356): #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 8356): #12     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259:13)
I/flutter ( 8356): #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 8356): #14     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:737:15)
I/flutter ( 8356): #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 8356): #16     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:737:15)
I/flutter ( 8356): #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 8356): #18     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter ( 8356): #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 8356): #20     _RenderSingleChildViewport.performLayout (package:flutter/src/widgets/single_child_scroll_view.dart:497:13)
I/flutter ( 8356): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 8356): #22     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8356): #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 8356): #24     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8356): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 8356): #26     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8356): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 8356): #28     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8356): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 8356): #30     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8356): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 8356): #32     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8356): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 8356): #34     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8356): #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 8356): #36     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8356): #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 8356): #38     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8356): #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 8356): #40     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:385:13)
I/flutter ( 8356): #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 8356): #42     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8356): #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 8356): #44     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8356): #45     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1206:11)
I/flutter ( 8356): #46     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 8356): #47     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8356): #48     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 8356): #49     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8356): #50     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 8356): #51     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:165:27)
I/flutter ( 8356): #52     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 8356): #53     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:407:13)
I/flutter ( 8356): #54     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1322:12)
I/flutter ( 8356): #55     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1240:20)
I/flutter ( 8356): #56     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 8356): #57     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8356): #58     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 8356): #59     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8356): #60     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 8356): #61     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8356): #62     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 8356): #63     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8356): #64     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 8356): #65     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8356): #66     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 8356): #67     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8356): #68     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 8356): #69     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8356): #70     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 8356): #71     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8356): #72     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 8356): #73     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8356): #74     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 8356): #75     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
I/flutter ( 8356): #76     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 8356): #77     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8356): #78     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 8356): #79     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8356): #80     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 8356): #81     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8356): #82     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 8356): #83     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8356): #84     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 8356): #85     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
I/flutter ( 8356): #86     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 8356): #87     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8356): #88     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 8356): #89     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8356): #90     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 8356): #91     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8356): #92     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 8356): #93     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8356): #94     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 8356): #95     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8356): #96     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 8356): #97     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3013:14)
I/flutter ( 8356): #98     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 8356): #99     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
I/flutter ( 8356): #100    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1519:7)
I/flutter ( 8356): #101    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:766:18)
I/flutter ( 8356): #102    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:347:19)
I/flutter ( 8356): #103    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
I/flutter ( 8356): #104    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
I/flutter ( 8356): #105    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
I/flutter ( 8356): #106    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
I/flutter ( 8356): #107    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:864:5)
I/flutter ( 8356): #111    _invoke (dart:ui/hooks.dart:219:10)
I/flutter ( 8356): #112    _drawFrame (dart:ui/hooks.dart:178:3)
I/flutter ( 8356): (elided 3 frames from package dart:async)
I/flutter ( 8356):
I/flutter ( 8356): The following RenderObject was being processed when the exception was fired:
I/flutter ( 8356):   _RenderDecoration#1c2bc NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 8356):   creator: _Decorator ← InputDecorator ← AnimatedBuilder ← Listener ← RawGestureDetector ←
I/flutter ( 8356):   TextSelectionGestureDetector ← IgnorePointer ← Semantics ← TextField ← ConstrainedBox ← Container
I/flutter ( 8356):   ← Column ← ⋯
I/flutter ( 8356):   parentData: <none> (can use size)
I/flutter ( 8356):   constraints: BoxConstraints(w=0.1, h=0.1)
I/flutter ( 8356):   size: MISSING
I/flutter ( 8356): This RenderObject had the following descendants (showing up to depth 5):
I/flutter ( 8356):   RenderRepaintBoundary#f75ef NEEDS-PAINT
I/flutter ( 8356):     RenderRepaintBoundary#33ae8 NEEDS-PAINT
I/flutter ( 8356):       RenderCustomPaint#25498 NEEDS-PAINT
I/flutter ( 8356):         RenderRepaintBoundary#2642a NEEDS-PAINT
I/flutter ( 8356):           RenderPointerListener#1f463 NEEDS-PAINT
I/flutter ( 8356):   RenderConstrainedBox#f1d8f relayoutBoundary=up1 NEEDS-PAINT
I/flutter ( 8356):   RenderSemanticsAnnotations#6f1d4 relayoutBoundary=up1 NEEDS-PAINT
I/flutter ( 8356):     RenderSemanticsAnnotations#72b15 relayoutBoundary=up2 NEEDS-PAINT
I/flutter ( 8356):       RenderExcludeSemantics#cb9c7 relayoutBoundary=up3 NEEDS-PAINT
I/flutter ( 8356):         RenderParagraph#6f37d relayoutBoundary=up4 NEEDS-PAINT
I/flutter ( 8356):   RenderCustomPaint#318f3 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 8356): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 8356): Another exception was thrown: RenderBox was not laid out: _RenderDecoration#1c2bc NEEDS-PAINT
I/flutter ( 8356): Another exception was thrown: RenderBox was not laid out: RenderPointerListener#2faf9 NEEDS-PAINT
I/flutter ( 8356): Another exception was thrown: RenderBox was not laid out: RenderIgnorePointer#8a78d NEEDS-PAINT
I/flutter ( 8356): Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#8f30f NEEDS-PAINT
I/flutter ( 8356): Another exception was thrown: RenderBox was not laid out: RenderConstrainedBox#36fc7 relayoutBoundary=up20 NEEDS-PAINT
I/flutter ( 8356): Another exception was thrown: RenderBox was not laid out: RenderFlex#94a7b relayoutBoundary=up19 NEEDS-PAINT
I/flutter ( 8356): Another exception was thrown: RenderBox was not laid out: RenderFlex#2ce5b relayoutBoundary=up18 NEEDS-PAINT
I/flutter ( 8356): Another exception was thrown: RenderBox was not laid out: RenderPadding#51ee6 relayoutBoundary=up17 NEEDS-PAINT
I/flutter ( 8356): Another exception was thrown: RenderBox was not laid out: _RenderSingleChildViewport#e7208 relayoutBoundary=up16 NEEDS-PAINT
I/flutter ( 8356): Another exception was thrown: RenderBox was not laid out: RenderIgnorePointer#b5598 relayoutBoundary=up15 NEEDS-PAINT
I/flutter ( 8356): Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#86859 relayoutBoundary=up14 NEEDS-PAINT
I/flutter ( 8356): Another exception was thrown: RenderBox was not laid out: RenderPointerListener#6fb81 relayoutBoundary=up13 NEEDS-PAINT
I/flutter ( 8356): Another exception was thrown: RenderBox was not laid out: RenderSemanticsGestureHandler#fb468 relayoutBoundary=up12 NEEDS-PAINT
I/flutter ( 8356): Another exception was thrown: RenderBox was not laid out: RenderPointerListener#1d2e2 relayoutBoundary=up11 NEEDS-PAINT
I/flutter ( 8356): Another exception was thrown: RenderBox was not laid out: _RenderScrollSemantics#29eb1 relayoutBoundary=up10 NEEDS-PAINT
I/flutter ( 8356): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#a92a3 relayoutBoundary=up9 NEEDS-PAINT
I/flutter ( 8356): Another exception was thrown: RenderBox was not laid out: RenderCustomPaint#6f809 relayoutBoundary=up8 NEEDS-PAINT
I/flutter ( 8356): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#17117 relayoutBoundary=up7 NEEDS-PAINT
I/flutter ( 8356): Another exception was thrown: RenderBox was not laid out: RenderPositionedBox#1038f relayoutBoundary=up6 NEEDS-PAINT
I/flutter ( 8356): Another exception was thrown: RenderBox was not laid out: _RenderInkFeatures#68fd7 relayoutBoundary=up5 NEEDS-PAINT
I/flutter ( 8356): Another exception was thrown: RenderBox was not laid out: RenderPhysicalModel#e0921 relayoutBoundary=up4 NEEDS-PAINT
I/flutter ( 8356): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#e52a8 relayoutBoundary=up3 NEEDS-PAINT
I/flutter ( 8356): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 470 pos 12: 'child.hasSize': is not true.
I/flutter ( 8356): Another exception was thrown: NoSuchMethodError: The method 'debugAssertIsValid' was called on null.
I/flutter ( 8356): Another exception was thrown: NoSuchMethodError: The method 'debugAssertIsValid' was called on null.
I/flutter ( 8356): Another exception was thrown: BoxConstraints has a negative minimum height.
I/flutter ( 8356): Another exception was thrown: NoSuchMethodError: The getter 'visible' was called on null.
I/flutter ( 8356): Another exception was thrown: NoSuchMethodError: The method 'debugAssertIsValid' was called on null.
I/flutter ( 8356): Another exception was thrown: BoxConstraints has a negative minimum height.
I/flutter ( 8356): Another exception was thrown: NoSuchMethodError: The getter 'visible' was called on null.
I/flutter ( 8356): Another exception was thrown: NoSuchMethodError: The method 'debugAssertIsValid' was called on null.
I/flutter ( 8356): Another exception was thrown: BoxConstraints has a negative minimum height.
I/flutter ( 8356): Another exception was thrown: NoSuchMethodError: The getter 'visible' was called on null
```

**Comment by iqbalmineraltown** [comment]
still facing this on 1.3.6

**Comment by Moonlight217** [comment]
still no solution to this issue?
